version: '3'
services:
  node:
    image: midnightntwrk/node:latest
    ports:
      - "9944:9944"
  indexer:
    image: midnightntwrk/indexer-standalone:latest
    ports:
      - "8088:8088"
  proof-server:
    image: midnightntwrk/proof-server:latest
    command: ["midnight-proof-server", "--network", "undeployed", "--verbose"]
    ports:
      - "6300:6300"
    environment:
      RUST_BACKTRACE: "full"
      RUST_LOG: "trace"
